image_repo: public.ecr.aws/m5q3e4b2/prow
images:
    auto-generate-controllers: prow-auto-generate-controllers-0.0.33
    auto-update-controllers: prow-auto-update-controllers-0.0.24
    build-prow-images: prow-build-prow-images-0.0.58
    controller-release-tag: prow-controller-release-tag-0.0.24
    deploy: prow-deploy-0.0.35
    docs: prow-docs-0.0.29
    integration-test: prow-integration-0.0.45
    olm-bundle-pr: prow-olm-bundle-pr-0.0.25
    olm-test: prow-olm-test-0.0.24
    scan-controllers-cve: prow-scan-controllers-cve-0.0.18
    soak-test: prow-soak-0.0.23
    unit-test: prow-unit-0.0.26
    upgrade-go-version: prow-upgrade-go-version-0.0.24
    verify-attribution: prow-verify-attribution-0.0.23
