image_repo: public.ecr.aws/m5q3e4b2/prow
images:
    auto-generate-controllers: prow-auto-generate-controllers-0.0.36
    auto-update-controllers: prow-auto-update-controllers-0.0.27
    build-prow-images: prow-build-prow-images-0.0.62
    controller-release-tag: prow-controller-release-tag-0.0.27
    deploy: prow-deploy-0.0.38
    deploy-docs: prow-deploy-docs-0.0.7
    docs: prow-docs-0.0.32
    integration-test: prow-integration-0.0.46
    olm-bundle-pr: prow-olm-bundle-pr-0.0.28
    olm-test: prow-olm-test-0.0.27
    scan-controllers-cve: prow-scan-controllers-cve-0.0.21
    soak-test: prow-soak-0.0.26
    unit-test: prow-unit-0.0.29
    upgrade-go-version: prow-upgrade-go-version-0.0.27
    verify-attribution: prow-verify-attribution-0.0.26
