image_repo: public.ecr.aws/m5q3e4b2/prow
images:
    auto-generate-controllers: prow-auto-generate-controllers-0.0.35
    auto-update-controllers: prow-auto-update-controllers-0.0.26
    build-prow-images: prow-build-prow-images-0.0.61
    controller-release-tag: prow-controller-release-tag-0.0.26
    deploy: prow-deploy-0.0.37
    deploy-docs: prow-deploy-docs-0.0.6
    docs: prow-docs-0.0.31
    integration-test: prow-integration-0.0.45
    olm-bundle-pr: prow-olm-bundle-pr-0.0.27
    olm-test: prow-olm-test-0.0.26
    scan-controllers-cve: prow-scan-controllers-cve-0.0.20
    soak-test: prow-soak-0.0.25
    unit-test: prow-unit-0.0.28
    upgrade-go-version: prow-upgrade-go-version-0.0.26
    verify-attribution: prow-verify-attribution-0.0.25
