image_repo: public.ecr.aws/m5q3e4b2/prow
images:
    auto-generate-controllers: prow-auto-generate-controllers-0.0.34
    auto-update-controllers: prow-auto-update-controllers-0.0.25
    build-prow-images: prow-build-prow-images-0.0.60
    controller-release-tag: prow-controller-release-tag-0.0.25
    deploy: prow-deploy-0.0.36
    deploy-docs: prow-deploy-docs-0.0.5
    docs: prow-docs-0.0.30
    integration-test: prow-integration-0.0.48
    olm-bundle-pr: prow-olm-bundle-pr-0.0.26
    olm-test: prow-olm-test-0.0.25
    scan-controllers-cve: prow-scan-controllers-cve-0.0.19
    soak-test: prow-soak-0.0.24
    unit-test: prow-unit-0.0.27
    upgrade-go-version: prow-upgrade-go-version-0.0.25
    verify-attribution: prow-verify-attribution-0.0.24
