# This config is used to generate `jobs.yaml` file using `jobs_factory.py` and
# the jinja2 templates.

# Adding a service to the `aws_services` array will enable CI/CD

# List of AWS services supported in ACK testing infrastructure.
aws_services:
- acmpca
- apigatewayv2
- applicationautoscaling
- cloudtrail
- cloudwatch
- cloudwatchlogs
- dynamodb
- ec2
- ecr
- eks
- elasticache
- emrcontainers
- iam
- kms
- lambda
- memorydb
- mq
- opensearchservice
- rds
- route53
- s3
- sagemaker
- sfn
- sns

# List of AWS services onboarded for soak testing, executing in their Prow
# cluster on every release
soak_test_on_release_service_names: []

# List of AWS services whose controller gets generated and e2e tested whenever
# there is a new code-generator change.
# These controllers are generated and tested to validate that changes in code-generator
# are not breaking changes for service controllers. This helps surface any early
# issues with code-generator release.
# Since there can be some breaking changes, these tests are marked optional for
# prow merge criteria.
code_gen_presubmit_services:
- dynamodb
- ecr
- s3
