#This config is used to generate 'jobs.yaml' file from 'jobs_factory.py' using jinja2 templates.

# list of aws services supported in ACK
aws_services:
- apigatewayv2
- applicationautoscaling
- dynamodb
- ecr
- elasticache
- elasticsearchservice
- kms
- mq
- rds
- s3
- sagemaker
- sfn
- sns
- sqs
- ec2

# list of aws services onboarded for soak test execution from prow cluster on every release
soak_test_on_release_service_names:
- ecr