# This config is used to generate `jobs.yaml` file using `generator.go` and
# the Go templates.

# Adding a service to the `aws_services` array will enable CI/CD

# List of AWS services supported in ACK testing infrastructure.
aws_services:
- acm
- acmpca
- apigateway
- apigatewayv2
- applicationautoscaling
- athena
- autoscaling
- backup
- batch
- bedrock
- bedrockagent
- bedrockagentcorecontrol
- cloudfront
- cloudtrail
- cloudwatch
- cloudwatchevents
- cloudwatchlogs
- codeartifact
- cognitoidentityprovider
- documentdb
- dsql
- dynamodb
- ec2
- ecr
- ecrpublic
- ecs
- efs
- eks
- elasticache
- elbv2
- emrcontainers
- eventbridge
- firehose
- globalaccelerator
- glue
- iam
- kafka
- kinesis
- kms
- keyspaces
- lambda
- memorydb
- mq
- networkfirewall
- opensearchservice
- opensearchserverless
- organizations
- pipes
- prometheusservice
- quicksight
- ram
- rds
- recyclebin
- route53
- route53resolver
- s3
- s3control
- sagemaker
- secretsmanager
- servicecatalog
- ses
- sfn
- sns
- sqs
- ssm
- transfer
- wafv2

# List of service that will execute a set of tests for CARM
# These service need a CARM_ENABLED environment variable set to true
carm_test_services:
- ecr

# List of service that will execute a set of tests for IAM Role Selector (IRS)
# These service need a IAMRoleSelector feature gate to be set to true
irs_test_services:
- sqs

# List of AWS services onboarded for soak testing, executing in their Prow
# cluster on every release
soak_test_on_release_service_names: []

# List of AWS services whose controller gets generated and e2e tested whenever
# there is a new code-generator change.
# These controllers are generated and tested to validate that changes in code-generator
# are not breaking changes for service controllers. This helps surface any early
# issues with code-generator release.
# Since there can be some breaking changes, these tests are marked optional for
# prow merge criteria.
code_gen_presubmit_services:
- acm
- apigatewayv2
- cloudfront
- documentdb
- dynamodb
- ec2
- ecr
- efs
- eks
- eventbridge
- iam
- lambda
- pipes
- prometheusservice
- s3

runtime_presubmit_services:
- ecr
- iam
- s3
- ec2
- sagemaker
- sqs

# List of AWS services whose controller gets generated and e2e tested whenever
# there is a new `acktest` library change.
acktest_presubmit_services:
- ecr
- iam
- s3
